# Generated by Django 3.2.7 on 2021-12-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('caption', models.TextField()),
            ],
        ),
    ]
