# Generated by Django 3.2.7 on 2021-12-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffadmin', '0003_remove_happystories_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HappyStories',
        ),
    ]
