# Generated by Django 3.2.7 on 2021-12-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffadmin', '0005_happystories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
