# Generated by Django 3.2.7 on 2021-12-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('valdity', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('order', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('tax', models.CharField(max_length=50)),
                ('printedView', models.CharField(max_length=50)),
            ],
        ),
    ]
