# Generated by Django 3.2.7 on 2021-12-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phoneNumber', models.BigIntegerField()),
                ('profileFor', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('martialStatus', models.CharField(blank=True, default='never married', max_length=50, null=True)),
                ('motherTounge', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('income', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('states', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalInfotb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('complexion', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(max_length=100)),
                ('bodyType', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('smoke', models.CharField(max_length=100)),
                ('drink', models.CharField(max_length=100)),
                ('physicallyImpaired', models.CharField(max_length=100)),
                ('dressStyle', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfotb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherName', models.CharField(max_length=20)),
                ('motherOcuupation', models.CharField(max_length=30)),
                ('fatherName', models.CharField(max_length=20)),
                ('fatherOcuupation', models.CharField(max_length=30)),
                ('no_of_brothers', models.IntegerField()),
                ('no_of_brothers_married', models.IntegerField()),
                ('no_of_sisters', models.IntegerField()),
                ('no_of_sisters_married', models.IntegerField()),
                ('familyValue', models.CharField(max_length=20)),
                ('familyStatus', models.CharField(max_length=20)),
                ('familyType', models.CharField(max_length=20)),
                ('familyIncome', models.IntegerField()),
                ('nativeLocation', models.CharField(max_length=30)),
                ('medicalHistory', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInfotb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('languagesKnown', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
