# Generated by Django 3.2.7 on 2021-12-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinfotb',
            name='user',
        ),
        migrations.RemoveField(
            model_name='physicalinfotb',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
        migrations.DeleteModel(
            name='EducationalInfotb',
        ),
        migrations.DeleteModel(
            name='FamilyInfotb',
        ),
        migrations.DeleteModel(
            name='PhysicalInfotb',
        ),
        migrations.DeleteModel(
            name='profiles',
        ),
    ]
