# Generated by Django 3.2.7 on 2021-12-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='bodyType',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='complexion',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='dressStyle',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='familyIncome',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='familyStatus',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='familyType',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='familyValue',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='fatherName',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='fatherOcuupation',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='languagesKnown',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='medicalHistory',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='motherName',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='motherOcuupation',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='nativeLocation',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='no_of_brothers',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='no_of_brothers_married',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='no_of_sisters',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='no_of_sisters_married',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='physicallyImpaired',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='smoke',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='weight',
        ),
        migrations.CreateModel(
            name='PhysicalInfotb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('complexion', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(max_length=100)),
                ('bodyType', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('smoke', models.CharField(max_length=100)),
                ('drink', models.CharField(max_length=100)),
                ('physicallyImpaired', models.CharField(max_length=100)),
                ('dressStyle', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfotb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherName', models.CharField(max_length=20)),
                ('motherOcuupation', models.CharField(max_length=30)),
                ('fatherName', models.CharField(max_length=20)),
                ('fatherOcuupation', models.CharField(max_length=30)),
                ('no_of_brothers', models.IntegerField()),
                ('no_of_brothers_married', models.IntegerField()),
                ('no_of_sisters', models.IntegerField()),
                ('no_of_sisters_married', models.IntegerField()),
                ('familyValue', models.CharField(max_length=20)),
                ('familyStatus', models.CharField(max_length=20)),
                ('familyType', models.CharField(max_length=20)),
                ('familyIncome', models.IntegerField()),
                ('nativeLocation', models.CharField(max_length=30)),
                ('medicalHistory', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInfotb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('languagesKnown', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
