# Generated by Django 3.2.7 on 2021-12-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_educationalinfotb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
