# Generated by Django 3.2.7 on 2021-12-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userlanguages_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguages',
            name='user',
        ),
    ]
