# Generated by Django 3.2.7 on 2021-12-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userlanguages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinfotb',
            name='languagesKnown',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='UserLanguages',
        ),
    ]
