# Generated by Django 3.2.7 on 2021-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211227_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalinfotb',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
