# Generated by Django 3.2.7 on 2021-12-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_physicalinfotb_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinfotb',
            name='no_of_brothers',
        ),
        migrations.RemoveField(
            model_name='familyinfotb',
            name='no_of_brothers_married',
        ),
        migrations.RemoveField(
            model_name='familyinfotb',
            name='no_of_sisters',
        ),
        migrations.RemoveField(
            model_name='familyinfotb',
            name='no_of_sisters_married',
        ),
        migrations.AddField(
            model_name='familyinfotb',
            name='noofBrothers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyinfotb',
            name='noofBrothersMarried',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyinfotb',
            name='noofSisters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyinfotb',
            name='noofSistersMarried',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='familyIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='familyStatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='familyType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='familyValue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='fatherName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='fatherOcuupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='medicalHistory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='motherName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='motherOcuupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='nativeLocation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
