# Generated by Django 3.2.7 on 2021-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20211227_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfotb',
            name='familyIncome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
