# Generated by Django 3.2.7 on 2021-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20211227_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfotb',
            name='noofBrothers',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='noofBrothersMarried',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='noofSisters',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familyinfotb',
            name='noofSistersMarried',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
