# Generated by Django 3.2.7 on 2021-12-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20211227_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactInfotb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileCode', models.CharField(max_length=50)),
                ('phoneNumber', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('residenceIn', models.CharField(max_length=30)),
                ('otherLocation', models.CharField(max_length=30)),
                ('pincode', models.BigIntegerField()),
                ('whatsappCode', models.CharField(max_length=50)),
                ('whatsappNumber', models.BigIntegerField()),
            ],
        ),
    ]
