# Generated by Django 3.2.7 on 2021-12-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_contactinfotb_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfotb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(max_length=200)),
                ('interest', models.CharField(max_length=200)),
                ('describedProfile', models.TextField()),
                ('proofType', models.CharField(max_length=30)),
                ('proofNumber', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
