# Generated by Django 3.2.7 on 2021-12-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_otherinfotb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatnerPrefertb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookingFor', models.CharField(blank=True, max_length=200, null=True)),
                ('complexion', models.CharField(blank=True, max_length=200, null=True)),
                ('livingIn', models.CharField(blank=True, max_length=200, null=True)),
                ('residentialState', models.CharField(blank=True, max_length=200, null=True)),
                ('ageFrom', models.IntegerField()),
                ('ageTo', models.IntegerField()),
                ('heightFrom', models.IntegerField()),
                ('heightTo', models.IntegerField()),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('motherTongue', models.CharField(blank=True, max_length=200, null=True)),
                ('expectation', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=200, null=True)),
                ('caste', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
