# Generated by Django 3.2.7 on 2021-12-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_patnerprefertb'),
    ]

    operations = [
        migrations.AddField(
            model_name='patnerprefertb',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
