# Generated by Django 3.2.7 on 2021-12-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_patnerprefertb_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patnerprefertb',
            name='heightFrom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patnerprefertb',
            name='heightTo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
