# Generated by Django 3.2.7 on 2021-12-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20211228_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patnerprefertb',
            name='expectation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
