from django.urls import path
from .import views
urlpatterns = [
    path('', views.indexFun, name='index'),
    path('signup/', views.signupFun, name='signup'),
    path('login/', views.loginFun, name='login'),
    path('userhome/', views.homeFun, name='userhome'),
    path('logout/', views.logoutFun, name='logout'),
    path('master/', views.userFun, name='userdashboard'),
    path('myprofile/', views.myprofileFun, name='myprofile'),
    path('mymatches/', views.mymatchesFun, name='mymatches'),
    path('shortlist/', views.shortlistFun, name='shortlist'),
    path('manageprofile/', views.manageprofileFun, name='manageprofile'),
    path('packageuser/', views.packageuserFun, name='packageuser'),
    path('searchbasic/', views.searchbasicFun, name='searchbasic'),
    path('searcheducation/', views.searcheducationFun, name='searcheducation'),
    path('searchoccupation/', views.searchoccupationFun, name='searchoccupation'),
    path('searchid/', views.searchidFun, name='searchid'),
    path('searchadvanced/', views.searchadvancedFun, name='searchadvanced'),
    path('managephotos/', views.managephotosFun, name='managephotos'),
    path('expressinterest/', views.expressinterestFun, name='expressinterest'),
    path('photorequest/', views.photorequestFun, name='photorequest'),
    path('messagesuser/', views.messagesuserFun, name='messagesuser'),
    path('expresseduser/', views.expresseduserFun, name='expresseduser'),
    path('recieveduser/', views.recieveduserFun, name='recieveduser'),
    path('dashboard/', views.dashboardFun, name='dashboard'),
    path('basicinformation/', views.basicinformationFun, name='basicinformation'),
    path('basicupdate/', views.basicupdateFun, name='basicupdate'),
    path('educationalinformation/', views.educationalinformationFun,
         name='educationalinformation'),
    path('eduUpdate/', views.eduUpdateFun,
         name='eduUpdate'),
    path('physicalinformation/', views.physicalinformationFun,
         name='physicalinformation'),
    path('physicalupdate/', views.physicalUpdateFun,
         name='physicalupdate'),
    path('familyinformation/', views.familyinformationFun,
         name='familyinformation'),
    path('familyupdate/', views.familyUpdateFun,
         name='familyupdate'),
    path('contactinformation/', views.contactinformationFun,
         name='contactinformation'),
    path('contactupdate/', views.contactUpdateFun,
         name='contactupdate'),
    path('otherinformation/', views.otherinformationFun, name='otherinformation'),
    path('otherupdate/', views.otherUpdateFun, name='otherupdate'),
    path('patnerpreference/', views.patnerpreferenceFun, name='patnerpreference'),
    path('patnerupdate/', views.patnerUpdateFun, name='patnerupdate'),
    path('mypackage/', views.mypackageFun, name='mypackage'),
    path('photoreqreceived/', views.photoreqreceivedFun, name='photoreqreceived'),
    path('photoreqsent/', views.photoreqsentFun, name='photoreqsent'),
    path('deleteprofile/', views.deleteprofileFun, name='deleteprofile'),
    path('profilevisit/', views.profilevisitFun, name='profilevisit'),
    path('printprofile/', views.printprofileFun, name='printprofile'),
    path('viewprofile/', views.viewprofileFun, name='viewprofile'),
    path('viewfullprofil/e', views.viewfullprofileFun, name='viewfullprofile'),
    # path('', views.Fun, name=''),
    # path('', views.Fun, name=''),
    # path('', views.Fun, name=''),
    # path('', views.Fun, name=''),
    # path('', views.Fun, name=''),
    # path('', views.Fun, name=''),
    # path('', views.Fun, name=''),
    # path('', views.Fun, name=''),
    # path('',views.Fun,name=''),
    # path('',views.Fun,name=''),

]
